name: 'Hello World'
on:
  workflow_dispatch:
jobs:
  hello_world_job:
    runs-on: self-hosted
    name: A job to say hello
    steps:
      - uses: actions/checkouts@v3
      - id: foo
        uses: ./.github/actions
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash